name: Run tests
on:
  push:
    branches:
      - mainnet
      - testnet
      - "release/**"
  pull_request:
    branches:
      - mainnet
      - testnet
      - "release/**"
      - "feat/**"

permissions:
  packages: read

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  nodejs:
    runs-on: [self-hosted, dockerize]
    steps:
      - id: 'gh-app'
        name: 'Get Token'
        uses: 'tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a' #v1.7.0
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_PRIVATE_KEY }}

      - uses: actions/checkout@v4.1.1
        with:
          submodules: recursive
          token: ${{ steps.gh-app.outputs.token }}

      - name: "Setup Node"
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 #v3.4.1
        with:
          node-version: v16.16.0

      - name: Github private package token in npmrc
        run: |
          echo "@axieinfinity:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: "Run install"
        uses: borales/actions-yarn@97ba8bebfe5b549bb7999261698a52a81fd62f1b #v4.2.0
        with:
          cmd: install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@cb603ca0abb544f301eaed59ac0baf579aa6aecf #v1.0.10

      - name: "Run Compile"
        uses: borales/actions-yarn@97ba8bebfe5b549bb7999261698a52a81fd62f1b #v4.2.0
        with:
          cmd: compile

      - name: "Run Test"
        uses: borales/actions-yarn@97ba8bebfe5b549bb7999261698a52a81fd62f1b #v4.2.0
        with:
          cmd: test:ci
